/* tslint:disable */
/* eslint-disable */
/**
 * Peba Finance API
 * API for finance management with income and expenses tracking
 *
 * The version of the OpenAPI document: v1
 * Contact: hackmann657@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

